"""Write-side admin endpoints for Server B Claude marketplace (PR-5a).

Implements spec.md section 7.2 write endpoints. Mirrors the auth + SSH-shell-out
pattern of routers/marketplace.py (PR-4 read side) but uses an *independent*
SSH user / key (settings.admin_user / settings.admin_ssh_key) so the readonly
channel cannot be abused to trigger writes (spec.md M11 closure).

All write operations are routed through Server B's
``/usr/local/bin/bifrost-admin-router.sh`` (PR-5a; forced-command on user
``bifrost-admin``). The router accepts only a closed verb whitelist:
``upload | tag-create | approve | curate | rerender``. Any other input is
rejected with exit code 2 and surfaces here as HTTP 502.

The upload envelope is a single JSON document piped to the admin-router over
stdin (the tarball travels as a base64-encoded string inside it):

    {
        "tarball_b64": "<base64 of the multipart tarball>",
        "manifest":    {<parsed manifest.yaml>},
        "audit_id":    "<UUID4 generated by bifrost-api>",
        "actor":       "<actor identifier; currently the X-Admin-Key truncated>"
    }

The server-side router is responsible for: tarball extraction, git clone of
the bare repo, commit + annotated tag creation, push, and audit-log emission.
Exit-code mapping (spec.md section 7.2):

    0  -> 200 OK
    2  -> 502 (forbidden verb / parse failure)
    9  -> 409 (tag/version conflict)
    *  -> 502 (other failure)

Timeouts surface as 504. Missing key file surfaces as 503.

DRY note: read/write routers keep separate users and exit-code mappings, while
the shared subprocess/key/timeout mechanics live in app.utils.ssh_runner.
"""

from __future__ import annotations

import base64
import json
import uuid
from typing import Any

import yaml
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from pydantic import BaseModel, Field

from ..config import Settings
from ..dependencies import get_settings, require_admin
from ..schemas import ApiResponse
from ..utils.ssh_runner import SshChannel, run_ssh_command

router = APIRouter(
    prefix="/marketplace/admin",
    tags=["内部 Marketplace (admin)"],
    dependencies=[Depends(require_admin)],
)


_MAX_TARBALL_BYTES = 50 * 1024 * 1024
_MANIFEST_REQUIRED_TOP_KEYS = (
    "version",
    "description",
    "license_id",
    "maintainers",
    "requires",
)
_ADMIN_ROUTER_VERBS = {"upload", "tag-create", "approve", "curate", "rerender"}


class ApproveBody(BaseModel):
    """Request payload for POST /marketplace/admin/approve."""

    plugin: str = Field(..., min_length=1, max_length=128)
    version: str = Field(..., min_length=1, max_length=64)
    decision: str = Field(..., pattern=r"^(approve|reject)$")


class CurateBody(BaseModel):
    """Request payload for POST /marketplace/admin/curate."""

    plugin: str = Field(..., min_length=1, max_length=128)
    action: str = Field(..., pattern=r"^(feature|deprecate|remove)$")


def _actor_token(x_admin_key: str) -> str:
    """Short non-secret identifier for audit log attribution.

    Truncated to 12 chars so the audit log never carries the full admin key.
    """
    return x_admin_key[:12] if x_admin_key else "anonymous"


async def _run_admin_command(
    settings: Settings,
    verb: str,
    args: list[str] | None = None,
    stdin_bytes: bytes | None = None,
) -> tuple[int, str, str]:
    """Run a whitelisted admin-router verb against Server B over SSH.

    Returns ``(returncode, stdout, stderr)``. Caller maps exit codes to HTTP
    status codes. Raises 503 if the key is missing, 504 on timeout, 503 if
    subprocess fails to spawn.
    """
    if verb not in _ADMIN_ROUTER_VERBS:
        raise HTTPException(
            status_code=502,
            detail=f"admin-router 拒绝未授权 verb: {verb}",
        )

    remote_command_parts = [verb, *(args or [])]
    remote_command = " ".join(remote_command_parts)

    result = await run_ssh_command(
        SshChannel(
            label=f"admin verb={verb}",
            user=settings.admin_user,
            host=settings.server_b_wg_ip,
            key_path=settings.admin_ssh_key,
            timeout_sec=settings.admin_ssh_timeout_sec,
            missing_key_detail="Server B 管理 SSH 通道未配置",
            timeout_detail="Server B 管理 SSH 请求超时",
            unavailable_detail="Server B 管理 SSH 通道不可用",
        ),
        remote_command,
        stdin_bytes=stdin_bytes,
    )
    return result.returncode, result.stdout, result.stderr


def _map_admin_exit_code(returncode: int, stdout: str, stderr: str) -> None:
    """Raise an HTTPException for any non-zero admin-router exit code.

    Mapping:
      0 -> no-op
      2 -> 502 (forbidden / parse failure)
      9 -> 409 (tag conflict)
      * -> 502 (other failure)
    """
    if returncode == 0:
        return
    stderr_snip = stderr.strip()[:300]
    if returncode == 2:
        raise HTTPException(
            status_code=502,
            detail=f"admin-router 拒绝命令: {stderr_snip or 'forbidden'}",
        )
    if returncode == 9:
        raise HTTPException(
            status_code=409,
            detail=f"plugin tag / version 冲突: {stderr_snip or 'tag already exists'}",
        )
    raise HTTPException(
        status_code=502,
        detail=f"admin-router 执行失败 (exit={returncode}): {stderr_snip}",
    )


def _validate_manifest(raw: bytes) -> dict[str, Any]:
    """Parse + structurally validate a manifest.yaml payload.

    Raises 422 for any failure. Returns the parsed dict on success.
    """
    if not raw:
        raise HTTPException(status_code=422, detail="manifest.yaml 为空")

    try:
        parsed = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        raise HTTPException(
            status_code=422, detail=f"manifest.yaml YAML 解析失败: {exc}"
        ) from exc

    if not isinstance(parsed, dict):
        raise HTTPException(
            status_code=422,
            detail="manifest.yaml 顶层必须是 mapping",
        )

    missing = [k for k in _MANIFEST_REQUIRED_TOP_KEYS if k not in parsed]
    if missing:
        raise HTTPException(
            status_code=422,
            detail=f"manifest.yaml 缺少必填字段: {', '.join(missing)}",
        )

    if not isinstance(parsed.get("version"), str) or not parsed["version"]:
        raise HTTPException(status_code=422, detail="manifest.yaml version 必须是非空字符串")
    if not isinstance(parsed.get("description"), str) or not parsed["description"]:
        raise HTTPException(status_code=422, detail="manifest.yaml description 必须是非空字符串")
    if not isinstance(parsed.get("license_id"), str) or not parsed["license_id"]:
        raise HTTPException(status_code=422, detail="manifest.yaml license_id 必须是非空字符串")
    if not isinstance(parsed.get("maintainers"), list) or not parsed["maintainers"]:
        raise HTTPException(status_code=422, detail="manifest.yaml maintainers 必须是非空数组")
    if not isinstance(parsed.get("requires"), dict):
        raise HTTPException(status_code=422, detail="manifest.yaml requires 必须是 mapping")
    return parsed


async def _read_upload_capped(upload: UploadFile, limit: int) -> bytes:
    """Read up to ``limit`` bytes from ``upload``; raise 422 if exceeded.

    Chunked read protects against ballooning process memory on hostile inputs.
    """
    chunks: list[bytes] = []
    total = 0
    while True:
        chunk = await upload.read(64 * 1024)
        if not chunk:
            break
        total += len(chunk)
        if total > limit:
            raise HTTPException(
                status_code=422,
                detail=f"tarball 超过 {limit // (1024 * 1024)}MB 限制",
            )
        chunks.append(chunk)
    return b"".join(chunks)


def _extract_plugin_name(manifest: dict[str, Any], fallback_filename: str | None) -> str:
    """Best-effort extraction of the plugin slug.

    Either ``manifest["name"]`` or a slug derived from the tarball filename.
    Fails closed (422) if neither yields a sane slug.
    """
    candidate = manifest.get("name") if isinstance(manifest.get("name"), str) else None
    if not candidate and fallback_filename:
        stem = fallback_filename
        for suffix in (".tar.gz", ".tgz", ".tar"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
                break
        if "-v" in stem:
            stem = stem.rsplit("-v", 1)[0]
        candidate = stem or None
    if not candidate:
        raise HTTPException(
            status_code=422,
            detail="manifest.yaml 缺 name 字段且无法从 tarball 文件名推导 plugin slug",
        )
    if not all(ch.isalnum() or ch in "-_" for ch in candidate):
        raise HTTPException(
            status_code=422,
            detail=f"plugin slug 含非法字符: {candidate}",
        )
    return candidate


@router.post("/upload", response_model=ApiResponse)
async def admin_upload(
    tarball: UploadFile = File(..., description="plugin tarball (.tar.gz, <= 50MB)"),
    manifest: UploadFile = File(..., description="manifest.yaml"),
    settings: Settings = Depends(get_settings),
    x_admin_key: str = Depends(require_admin),
) -> ApiResponse:
    """Receive a plugin tarball + manifest and forward to admin-router upload."""
    tarball_bytes = await _read_upload_capped(tarball, _MAX_TARBALL_BYTES)
    manifest_bytes = await _read_upload_capped(manifest, 1 * 1024 * 1024)
    parsed_manifest = _validate_manifest(manifest_bytes)
    plugin_name = _extract_plugin_name(parsed_manifest, tarball.filename)
    version = parsed_manifest["version"]

    audit_id = str(uuid.uuid4())
    envelope = {
        "tarball_b64": base64.b64encode(tarball_bytes).decode("ascii"),
        "manifest": parsed_manifest,
        "audit_id": audit_id,
        "actor": _actor_token(x_admin_key),
        "plugin": plugin_name,
        "version": version,
    }
    payload = json.dumps(envelope, separators=(",", ":")).encode("utf-8")

    returncode, stdout, stderr = await _run_admin_command(
        settings,
        "upload",
        args=[plugin_name, version],
        stdin_bytes=payload,
    )
    _map_admin_exit_code(returncode, stdout, stderr)

    tag_created = f"plugins/{plugin_name}/v{version}"
    return ApiResponse(
        success=True,
        data={
            "tag_created": tag_created,
            "render_triggered": True,
            "audit_id": audit_id,
            "stdout_snip": stdout.strip()[:200],
        },
    )


@router.post("/approve", response_model=ApiResponse)
async def admin_approve(
    body: ApproveBody,
    settings: Settings = Depends(get_settings),
    x_admin_key: str = Depends(require_admin),
) -> ApiResponse:
    """Record an approve/reject decision via admin-router approve verb."""
    audit_id = str(uuid.uuid4())
    envelope = {
        "audit_id": audit_id,
        "actor": _actor_token(x_admin_key),
        "plugin": body.plugin,
        "version": body.version,
        "decision": body.decision,
    }
    payload = json.dumps(envelope, separators=(",", ":")).encode("utf-8")

    returncode, stdout, stderr = await _run_admin_command(
        settings,
        "approve",
        args=[body.plugin, body.version, body.decision],
        stdin_bytes=payload,
    )
    _map_admin_exit_code(returncode, stdout, stderr)

    return ApiResponse(
        success=True,
        data={"ok": True, "audit_id": audit_id},
    )


@router.post("/curate", response_model=ApiResponse)
async def admin_curate(
    body: CurateBody,
    settings: Settings = Depends(get_settings),
    x_admin_key: str = Depends(require_admin),
) -> ApiResponse:
    """Mutate marketplace.json metadata (feature / deprecate / remove)."""
    audit_id = str(uuid.uuid4())
    envelope = {
        "audit_id": audit_id,
        "actor": _actor_token(x_admin_key),
        "plugin": body.plugin,
        "action": body.action,
    }
    payload = json.dumps(envelope, separators=(",", ":")).encode("utf-8")

    returncode, stdout, stderr = await _run_admin_command(
        settings,
        "curate",
        args=[body.plugin, body.action],
        stdin_bytes=payload,
    )
    _map_admin_exit_code(returncode, stdout, stderr)

    return ApiResponse(
        success=True,
        data={"ok": True, "audit_id": audit_id},
    )


@router.post("/rerender", response_model=ApiResponse)
async def admin_rerender(
    settings: Settings = Depends(get_settings),
    x_admin_key: str = Depends(require_admin),
) -> ApiResponse:
    """Trigger marketplace-render.path via admin-router rerender verb."""
    audit_id = str(uuid.uuid4())
    envelope = {
        "audit_id": audit_id,
        "actor": _actor_token(x_admin_key),
    }
    payload = json.dumps(envelope, separators=(",", ":")).encode("utf-8")

    returncode, stdout, stderr = await _run_admin_command(
        settings,
        "rerender",
        stdin_bytes=payload,
    )
    _map_admin_exit_code(returncode, stdout, stderr)

    return ApiResponse(
        success=True,
        data={"triggered": True, "audit_id": audit_id},
    )
